### ISSUE TITLE
paquettg/php-html-parser version 1.6.8 breaks Wallhaven. 

### ISSUE THREAD

**Issue by ryanrk** [ivkos/Wallhaven#3]
Can you put a hard release for "paquettg/php-html-parser": "1.6.4" as 1.6.8 seems to break line

Wallhaven.php:181

```
        $figures = $dom->find('figure.thumb');
```

**Comment by ivkos** [comment]
Thanks for the report, and sorry for replying a bit late. I'll check for a solution later.
